class app_topics:
    TOPIC_APP_MESSAGE = "App/Message"
    TOPIC_APP_STATUS = "App/Status"
    TOPIC_APP_ERROR = "App/Error"
    TOPIC_APP_SYSTEM = "App/System"
    TOPIC_APP_SYSTEM_STATUS = "App/System/Status"
    TOPIC_APP_TEST = "App/Test"
    TOPIC_APP_TEST_COMMAND = "App/Test/Command"
    TOPIC_APP_TEST_STATUS = "App/Test/Status"
    TOPIC_APP_TEST_LIMITSTATUS = "App/Test/LimitStatus"
    TOPIC_APP_TEST_RECORDSTATUS = "App/Test/RecordStatus"
    TOPIC_APP_TEST_LIST = "App/Test/List"
    TOPIC_APP_TEST_REPORTFILE = "App/Test/ReportFile"
    TOPIC_APP_TEST_REPORTTEMPLATES = "App/Test/ReportTemplates"
    TOPIC_APP_TEST_RECORDFILE = "App/Test/RecordFile"
    TOPIC_APP_TEST_REPORTNOTES = "App/Test/ReportNotes"
    TOPIC_APP_TEST_CHANNELS = "App/Test/Channels"
    TOPIC_APP_TEST_PARAMETERS = "App/Test/Parameters"
    TOPIC_APP_TEST_SIGNALS = "App/Test/Signals"
    TOPIC_APP_TEST_SIGNALDATA = "App/Test/SignalData"
    TOPIC_APP_TEST_COMPRESSED_SIGNALDATA = "App/Test/CompressedSignalData"
    TOPIC_APP_TEST_SIGNALPROPERTY = "App/Test/SignalProperty"
    TOPIC_APP_TEST_RUNFOLDER = "App/Test/RunFolder"
    TOPIC_APP_TEST_ADV_STATUS = "App/Test/AdvancedStatus"


class global_parameter_topics:
    TOPIC_GLOBAL_PARAMETER_REQUEST = "GlobalParameter/Request"
    TOPIC_GLOBAL_PARAMETER_RESPONSE = "GlobalParameter/Response"


class dsa_topics:
    TOPIC_DSA_TEST_COMMAND = "DSA/Test/Command"
    TOPIC_DSA_TEST_DSA_STATUS = "DSA/Test/DSAStatus"


class vcs_topics:
    TOPIC_VCS_TEST_COMMAND = "VCS/Test/Command"
    TOPIC_VCS_TEST_STAGE = "VCS/Test/Stage"
    TOPIC_VCS_TEST_SHAKER = "VCS/Test/Shaker"
    TOPIC_VCS_TEST_CONTROL_UPDATED = "VCS/Test/ControlUpdated"
    TOPIC_VCS_TEST_RANDOM_STATUS = "VCS/Test/RandomStatus"
    TOPIC_VCS_TEST_SINE_STATUS = "VCS/Test/SineStatus"
    TOPIC_VCS_TEST_SHOCK_STATUS = "VCS/Test/ShockStatus"
    TOPIC_VCS_TEST_TWR_STATUS = "VCS/Test/TWRStatus"


class thv_topics:
    TOPIC_THV_TEST_COMMAND = "THV/Test/Command"
    TOPIC_THV_TEST_TH_STATUS = "THV/Test/THStatus"
    TOPIC_THV_TEST_VT_STATUS = "THV/Test/VHStatus"


class command_key:
    Pause = "Pause"
    Continue = "Continue"
    Run = "Run"
    Stop = "Stop"
    Connect = "Connect"
    Disconnect = "Disconnect"
    StartRecord = "StartRecord"
    StopRecord = "StopRecord"
    SaveSignals = "SaveSignals"
    ResetAverage = "ResetAverage"
    RequestDetailStatus = "RequestDetailStatus"
    RequestSignalData = "RequestSignalData"
    RequestSignalProperty = "RequestSignalProperty"
    RequestReportFile = "RequestReportFile"
    RequestRunFolder = "RequestRunFolder"
    RequestRecordFile = "RequestRecordFile"
    ListReportNotes = "ListReportNotes"
    SetReportNotes = "SetReportNotes"
    LoadTest = "LoadTest"
    CreateTest = "CreateTest"
    DeleteTest = "DeleteTest"
    ListTest = "ListTest"
    GenerateReport = "GenerateReport"
    SetParameter = "SetParameter"
    ListGlobalParameters = "ListGlobalParameters"
    TriggerOn = "TriggerOn"
    TriggerOff = "TriggerOff"
    OutputOn = "OutputOn"
    OutputOff = "OutputOff"
    SetOutputParameters = "SetOutputParameters"
    SetOutputIndex = "SetOutputIndex"
    LimitOn = "LimitOn"
    LimitOff = "LimitOff"
    CheckOnly = "CheckOnly"
    Proceed = "Proceed"
    SaveHSignal = "SaveHSignal"
    SetLevel = "SetLevel"
    LevelUp = "LevelUp"
    LevelDown = "LevelDown"
    RestoreLevel = "RestoreLevel"
    NextEntry = "NextEntry"
    ShowPretest = "ShowPretest"
    AbortChecksOn = "AbortChecksOn"
    AbortChecksOff = "AbortChecksOff"
    ScheduleClockTimerOn = "ScheduleClockTimerOn"
    ScheduleClockTimerOff = "ScheduleClockTimerOff"
    ClosedLoopControlOn = "ClosedLoopControlOn"
    ClosedLoopControlOff = "ClosedLoopControlOff"
    SetFrequency = "SetFrequency"
    SetPhase = "SetPhase"
    HoldSweep = "HoldSweep"
    SweepUp = "SweepUp"
    SweepDown = "SweepDown"
    ReleaseSweep = "ReleaseSweep"
    IncreaseSpeed = "IncreaseSpeed"
    DecreaseSpeed = "DecreaseSpeed"
    RoRBandsOn = "RoRBandsOn"
    RoRBandsOff = "RoRBandsOff"
    SoRTonesOn = "SoRTonesOn"
    SoRTonesOff = "SoRTonesOff"
    SoRTonesHoldSweep = "SoRTonesHoldSweep"
    SoRTonesReleaseSweep = "SoRTonesReleaseSweep"
    SoRTonesSweepUp = "SoRTonesSweepUp"
    SoRTonesSweepDown = "SoRTonesSweepDown"
    InversePulseOn = "InversePulseOn"
    InversePulseOff = "InversePulseOff"
    SinglePulseOn = "SinglePulseOn"
    SinglePulseOff = "SinglePulseOff"
    OutputSinglePulse = "OutputSinglePulse"
    SetChannelTable = "SetChannelTable"
    SetRandomProfile = "SetRandomProfile"
    SetSineProfile = "SetSineProfile"
    SetShockProfile = "SetShockProfile"
    SetSchedule = "SetSchedule"
    RequestPeakFrequency = "RequestPeakFrequency"
    RequestPeakValue = "RequestPeakValue"
    StartTestSequence = "StartTestSequence"
    PauseTestSequence = "PauseTestSequence"
    ResumeTestSequence = "ResumeTestSequence"
    StopTestSequence = "StopTestSequence"
    NextTestSequence = "NextTestSequence"
